### ISSUE TITLE
File /b-merge/transcripts.fa does not exist or is empty

### ISSUE THREAD

**Issue by jfordonez** [abims-sbr/drap#1]
Hi,

I'm trying to run drap using the test data. I would like to ask for help regarding this matter:

So the error in 00-ERROR_AT_MERGE_STEP was: File oases_splA/b-merge/transcripts.fa does not exist or is empty

The "last" command in the 03-merge.sh is cat $f.cln | sed "s/>/>${g}_/;s|/.*||" >> oases_splA/b-merge/**transcripts.raw.fa** 

then the command in 04-clustering.sh looks for oases_splA/b-merge/**transcripts.fa**

I'm actually wondering if I'm missing something that converts the *raw.fa to *fa, which has been creating the error. I'm a noob in bioinfo btw. Thanks!

June

**Comment by pbordron** [comment]
Please get drap from http://www.sigenae.org/drap and contact original author if you need some help.
We do not provide support on this software.
