### ISSUE TITLE
Problem 00-assembly-complete

### ISSUE THREAD

**Issue by magadancito** [abims-sbr/drap#2]
Hi, first yours work in very good, congratulations, but I run runDrap successfully without errors, but the file 00-ASSEMBLY-COMPLETE is empty!! I do know what is this, thanks for all and excuse me for my bad English is not my native language.

**Comment by pbordron** [comment]
Please get drap from http://www.sigenae.org/drap and contact original author if you need some help.
We do not provide support on this software.
