### ISSUE TITLE
Perl handshake key error

### ISSUE THREAD

**Issue by pdimens** [abims-sbr/drap#3]
When using `self_chimeras_filter.pl` this error appears:

```bash
Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xcd00080)
```
I have a conda bioperl installation of `perl-bioperl`, `perl-bioperl-core`, and `perl-bioperl-run` and invoke `self_chimeras_filter.pl` within this environment. I'm unfamiliar with any kinds of handshakes in terms of errors. Perhaps you understand the nature of this error better than I do?

**Comment by pbordron** [comment]
Please get drap from http://www.sigenae.org/drap and contact original author if you need some help.
We do not provide support on this software.
