### ISSUE TITLE
Error in rmbt editing step

### ISSUE THREAD

**Issue by sneha100895** [abims-sbr/drap#4]
Hi, 
I am using DRAP for my de novo assembly. I keep getting an error at the rmbt editing step. When I troed running the 07-rmbt_editing.sh script alone I get the following error:
ERROR: ENV VARIABLE samtools_idx_res is not set

Could you please help me in resolving this error.

Thanks,
Sneha

**Comment by pbordron** [comment]
Please get drap from http://www.sigenae.org/drap and contact original author if you need some help.
We do not provide support on this software.
